### ISSUE TITLE
不懂PHP怎么使用您这个工具呢？

### ISSUE THREAD

**Issue by wsboy** [jormin/laravel-ddoc#2]
我是一个Java程序猿，最精遇到一个项目表非常的多而且字段也特别的多，我想借助您的工具导出数据字典，可是我不会php，不知道怎么搞？麻烦您能帮忙解答下，谢谢！！！

**Comment by jormin** [comment]
这个是`PHP`框架`Laravel`的一个扩展库，需要本地有`Web`环境，`Apache`或者`Nginx`都行，然后创建一个`Laravel`项目，引入本扩展，直接访问就行，如果你不会`PHP`的话，我可以帮你建一个项目，你`git clone`到本地后修改数据库配置项即可。

**需要说明下，这个扩展是读取数据库中表和字段的注释来生成文档。**

**Comment by wsboy** [comment]
麻烦你帮忙建个项目呗，🙏🙏🙏了

**Comment by jormin** [comment]
你在你机器上这样操作：

1. 装下`PHP`和`WEB`环境，可以装个集成环境[Xampp](https://www.apachefriends.org/download.html)，这样不用自己去修改配置，安装时如果本机已经有`MySql`，就取消勾选`MySql`。

2. 安装`Composer`，这是一个类似于`Maven`的依赖管理工具，具体安装方法可以参考我[这篇文章](https://blog.lerzen.com/articles/264be1c0-0fcb-11e7-a389-b10c47144db4)中`安装Composer`部分，一定要配置`Composer`国内镜像。

3. 克隆我新建的项目[jormin/ddoc](https://github.com/jormin/ddoc)，照着`readme`文档操作即可。

4. 给`Apache`配置一个`虚拟主机`：打开 `/path/to/xampp/apache/conf/extra/httpd-vhosts.conf`文件，在文档最后粘贴：

	```php
	<VirtualHost *:80>
	    ServerName ddoc.local.com
	    DocumentRoot "/path/to/your/cloned/project/public"
	</VirtualHost>
	```
	
	修改上面的`DocumentRoot`项，改为你克隆的项目下面的`public`目录，最好是绝对路径。

5. 本机的`hosts`文件中增加：

	```
	127.0.0.1 ddoc.local.com
	```

6. 浏览器访问

	```
	http://ddoc.local.com/ddoc
	```
