### ISSUE TITLE
求更新到laravel5.5

### ISSUE THREAD

**Issue by lonelv** [jormin/laravel-ddoc#4]
求更新到laravel5.5，很好用的包，项目升级到5.5后不能用了。。。

**Comment by jormin** [comment]
最新版本已经支持 `laravel 5.5`，`Composer 中国镜像`已经更新最新版本。

你试着在 `5.5` 中引入最新版本，有问题欢迎随时提 `Issue`。

感谢支持~

**Comment by lonelv** [comment]
大神威武！很喜欢这个轮子

**Comment by jormin** [comment]
感谢支持~
